name = "SpeechFeatures"
uuid = "6f3487c4-5ca2-4050-bfeb-2cf56df92307"
authors = ["Lucas Ondel <lucas.ondel@gmail.com"]
version = "0.2.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"

[compat]
FFTW = "1.3"
PaddedViews = "0.5"
julia = "1.5"
